### ISSUE TITLE
setTimeout() 

### ISSUE THREAD

**Issue by zhangtreefish** [garcrich/MyReads-A-Book-Tracking-App#1]
I tried the following on my app per [this link](https://stackoverflow.com/questions/36270422/reactjs-settimeout-not-working) and received no complaint from the compiler. 
```
componentDidMount() {
    setTimeout(()=>this.doSearch(this.state.query), 1500)
  } 
```
But I feel [debounce works better to limit ajax calls](http://blog.revathskumar.com/2016/02/reactjs-using-debounce-in-react-components.html)
On [syntheticEvent](https://facebook.github.io/react/docs/events.html)

[perform-debounce-in-react-js](https://stackoverflow.com/questions/23123138/perform-debounce-in-react-js)

**Comment by garcrich** [comment]
Thanks for the follow up! I used import DebounceInput from 'react-debounce-input' and it worked like a charm! Thanks for all your help.
